"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-pnr(2v7psdr5jt1ofg*p8416r%*19@oe_w)ij9kdgk3_-l606-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,app,web').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lms',                   # Aplikasi Simple LMS
    'silk',                  # Query profiling - Django Silk
    # Modul 7 — JWT Authentication
    'ninja_simple_jwt',
    # Modul 9 — Celery Scheduling
    'django_celery_beat',
    'django_celery_results',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',  # Intercept semua request untuk profiling
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Membaca kredensial dari environment variable (.env file)

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'simple_lms_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files (Upload: ImageField, FileField)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model - mengganti User default Django dengan model kita
# yang memiliki field 'role' (admin, instructor, student)
AUTH_USER_MODEL = 'lms.User'

# Logging - Diaktifkan agar connection.queries bisa melacak SQL queries
# (digunakan oleh demo_query.py untuk menghitung jumlah query N+1 vs optimized)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}


# ==============================================================================
# MODUL 7 — JWT Authentication (ninja-simple-jwt)
# Docs: https://github.com/humberto-pereira/ninja-simple-jwt
# ==============================================================================

NINJA_SIMPLE_JWT = {
    # Access token berlaku 30 menit (cukup untuk development, 5-15 menit untuk production)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    # Refresh token berlaku 7 hari
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Algoritma RSA (asymmetric) — lebih aman dari HS256
    'ALGORITHM': 'RS256',
}


# ==============================================================================
# MODUL 9 — Redis Cache & Rate Limiting
# Docs: https://github.com/jazzband/django-redis
# ==============================================================================

REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'IGNORE_EXCEPTIONS': True,   # Jangan crash jika Redis down
        },
        'KEY_PREFIX': 'simplelms',
        'TIMEOUT': 300,  # Default TTL: 5 menit
    }
}


# ==============================================================================
# MODUL 9 — MongoDB Activity Logs
# ==============================================================================

MONGO_URI = os.environ.get('MONGO_URI', 'mongodb://mongodb:27017')
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'simple_lms_logs')


# ==============================================================================
# MODUL 9 — Celery Configuration
# Broker: RabbitMQ | Backend: Redis
# ==============================================================================

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://guest:guest@rabbitmq:5672//')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Jakarta'
CELERY_ENABLE_UTC = True

# Celery Beat — Scheduled tasks disimpan di database (django_celery_beat)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Results — Simpan hasil task di database
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')

# Email backend — Console untuk development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@simplelms.id'


# ==============================================================================
# MODUL 10 — Media Files (File Upload)
# Konfigurasi untuk menyimpan file yang diupload user.
# Docs: https://docs.djangoproject.com/en/4.2/topics/files/
# ==============================================================================

# URL publik untuk mengakses media files
# Contoh: /media/course_images/python-course.jpg
MEDIA_URL = '/media/'

# Path absolut di filesystem tempat file disimpan
# Di Docker, direktori ini terdapat di dalam container
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images bawaan Django)
STATIC_URL = '/static/'
